@startuml Trend

start

repeat

if (Первый запуск) then (да)
    : Ициализация стартовых переменных;
endif

if (Есть позиция?) then (да)
    
    if (есть стоп?) then (нет)
        : выставляем стоп;
    else (да)
        : пытаемся улучшить;
    endif

else (no)
    : определяем старший тренд;
    : определяем младший тренд;

    if (тренды совпадают) then (да)
        : открытие позиции;
    endif
    
endif

@enduml